# Generated by Django 4.2.3 on 2023-08-09 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='carbs',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='fat',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='dietplan',
            name='protein',
            field=models.CharField(max_length=127, null=True),
        ),
    ]
