# Generated by Django 4.2.4 on 2023-08-10 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_dietplan_diet_plan_name_dietplan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='date_assigned',
            field=models.DateField(null=True),
        ),
    ]
