# Generated by Django 4.2.4 on 2023-08-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dietplan_date_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietplan',
            name='date_assigned',
            field=models.DateField(blank=True, null=True),
        ),
    ]
